### PR TITLE
GUI 1.0

### PR DESCRIPTION
**Pull request by OliverBrotchie**
A graphical user interface for phantom created so that people who are less technically skilled can still use it.

To build into exe ect run the command:  pgk phantom-GUI.js
For more info see: https://www.npmjs.com/package/pkg

The front end code is at lib/js/indexjs
I have used my own library - Interface.js - to create the console

lib and phantom exe are intended to be included in the same file when running phantom-GUI

### CODE REVIEW

**Comment by OliverBrotchie** [comment]
I cannot get it to run on macOS and hence I am re-writing it a an electron app instead of a basic web-app. https://www.electronjs.org/

I will be in touch soon...

**Comment by jhead** [comment]
Hey @OliverBrotchie, thanks for the contribution. We've got some ideas for a UI but no concrete plans yet. For what it's worth, we're probably going to avoid Electron just because of how resource intensive it tends to be. Either way, feel free to start up another repo and if you get something working, I'll happily add a link to it in our readme under a section for community projects/forks/etc.

**Comment by OliverBrotchie** [comment]
Okay no worries! Feel free to use anything from the UI or old code. It was all working, I was just struggling to find a way to package it into an exe. 

Good luck and I'll let you know when I get the electron app finished! 😊

**Comment by OliverBrotchie** [comment]
@jhead I have just finished and released the electron app! If you want to take a look at it, you can see it under my releases.

**Pull request closed without merging**
